# Generated by Django 4.0.2 on 2022-02-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexar',
            name='descricao',
            field=models.TextField(verbose_name='Resumo'),
        ),
    ]
