# Generated by Django 4.0.2 on 2022-02-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anexar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Tema da monografia')),
                ('descricao', models.TextField(verbose_name='Resumo')),
                ('arquivo_pdf', models.FileField(upload_to='uploads/')),
                ('publicacao', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
